### ISSUE TITLE
javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request;Caused by: java.lang.IllegalStateException: Connection is still allocated

### ISSUE THREAD

**Issue by idomon** [jersey/jersey#3549]
Run the following main method and getting stack traces:

 ```

import javax.ws.rs.client.Client;
import javax.ws.rs.client.ClientBuilder;
import javax.ws.rs.client.Invocation.Builder;
import javax.ws.rs.core.GenericType;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import org.glassfish.jersey.client.ClientProperties;

public class RestClientDemo {
	private Client client = ClientBuilder.newClient();
	public void send() {
		com.test.Response res0 = send(client, "service/car/query");
		System.out.println(res0.getResponseCode());
	}
	public static void main(String[] args) {
		RestClientDemo client = new RestClientDemo();
		RestClientDemo.ThreadDemo2 t1 = new RestClientDemo().new ThreadDemo2(client);
		Thread thread1 = new Thread(t1);
		thread1.start();
		Thread thread2 = new Thread(t1);
		thread2.start();
	}
	public static com.test.Response send(Client clie, String path) {
		String url = "http://localhost:8080";
		Response target = null;
		Builder invocationBuilder = null;
		invocationBuilder = clie.target(url).path(path)
				.request(MediaType.APPLICATION_JSON_TYPE);
		target = invocationBuilder.get();
		com.test.Response resp = null;
		invocationBuilder.property(ClientProperties.CONNECT_TIMEOUT, 60000);
		invocationBuilder.property(ClientProperties.READ_TIMEOUT, 60000);
		resp = target.readEntity(new GenericType<com.test.Response>() {});
		return resp;
	}
	class ThreadDemo2 implements Runnable {
		private RestClientDemo client;
		public ThreadDemo2(RestClientDemo client) {
			this.client = client;
		}
		public void run() {
			client.send();
		}
	}
}


```
```

Exception in thread "Thread-2" javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:289)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:454)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocationBuilder.get(ClientInvocationBuilder.java:157)
	at RestClientDemo.send(RestClientDemo.java:30)
	at RestClientDemo.send(RestClientDemo.java:13)
	at RestClientDemo$ThreadDemo2.run(RestClientDemo.java:43)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Connection is still allocated
	at org.apache.http.util.Asserts.check(Asserts.java:34)
	at org.apache.http.impl.conn.BasicHttpClientConnectionManager.getConnection(BasicHttpClientConnectionManager.java:266)
	at org.apache.http.impl.conn.BasicHttpClientConnectionManager$1.get(BasicHttpClientConnectionManager.java:217)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:190)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:285)
	... 6 more
```

**Comment by pavelbucek** [comment]
"resteasy" string is very suspicious - are you sure you are using jersey?

**Comment by idomon** [comment]
sorry,it's my fault.
