### ISSUE TITLE
Issue at runtime - Absent Code attribute in method that is not native or abstract in class file javax/ws/rs/core/MediaType

### ISSUE THREAD

**Issue by RamakriJaya** [jersey/jersey#3567]
Hi
We are writing a REST client to consume Restful webservices

Please let me know if someone is facing the issue and know the resolution. At runtime it fails in Client.create(config) .
The dependencies in pom.xml are 

		<dependency>
			<groupId>com.sun.jersey</groupId>
			<artifactId>jersey-server</artifactId>
			<version>1.8</version>
		</dependency>

		<dependency>
			<groupId>com.sun.jersey</groupId>
			<artifactId>jersey-json</artifactId>
			<version>1.8</version>
		</dependency>
		
		<dependency>
			<groupId>com.sun.jersey</groupId>
			<artifactId>jersey-client</artifactId>
			<version>1.8</version>
		</dependency>
		
      
        <dependency>
    <groupId>com.sun.jersey</groupId>
    <artifactId>jersey-bundle</artifactId>
    <version>1.8</version>
</dependency>

We have the sample client class

ClientConfig config = new DefaultClientConfig();
		config.getFeatures().put(JSONConfiguration.FEATURE_POJO_MAPPING,
				Boolean.TRUE);
		config.getFeatures().put(URLConnectionClientHandler.PROPERTY_HTTP_URL_CONNECTION_SET_METHOD_WORKAROUND, true);
		
		Client client = Client.create(config);
		WebResource webResource = client
				.resource("http://129.221.30.70:8080/abc-rs/secure/xxxService/xxxRetrieve");
		client.addFilter(new LoggingFilter(System.out));
		
		ObjectMapper mapper = new ObjectMapper();
		ClientResponse response = webResource.header("content-type", "application/json")
				.accept(MediaType.APPLICATION_JSON)
				.type(MediaType.APPLICATION_JSON).header("host", "xxx").header("token", authStr).header("office", "xxxx")
				 .header("station", "MxxSP").header("userId", "admin")
				.post(ClientResponse.class, mapper.writeValueAsString(xxRetrieveRequest));
		
		
		if (response.getStatus() != 201) {
		throw new RuntimeException("Failed : HTTP error code : "
		     + response.getStatus());
	}
		System.out.println(response.getStatus());
		System.out.println(response.getEntity(String.class));

Exception in thread "main" java.lang.ClassFormatError: Absent Code attribute in method that is not native or abstract in class file javax/ws/rs/core/MediaType
      at java.lang.ClassLoader.defineClass1(Native Method)
      at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
      at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
      at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
      at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
      at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
      at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
      at java.security.AccessController.doPrivileged(Native Method)
      at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
      at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
      at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
      at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
      at java.lang.Class.getDeclaredMethods0(Native Method)
      at java.lang.Class.privateGetDeclaredMethods(Class.java:2570)
      at java.lang.Class.getDeclaredMethods(Class.java:1855)
      at com.sun.jersey.core.reflection.MethodList.getAllDeclaredMethods(MethodList.java:70)
      at com.sun.jersey.core.reflection.MethodList.<init>(MethodList.java:64)
      at com.sun.jersey.core.spi.component.ComponentConstructor.getPostConstructMethods(ComponentConstructor.java:131)
      at com.sun.jersey.core.spi.component.ComponentConstructor.<init>(ComponentConstructor.java:123)
      at com.sun.jersey.core.spi.component.ProviderFactory.__getComponentProvider(ProviderFactory.java:165)
      at com.sun.jersey.core.spi.component.ProviderFactory.getComponentProvider(ProviderFactory.java:137)
      at com.sun.jersey.core.spi.component.ProviderServices.getComponent(ProviderServices.java:256)
      at com.sun.jersey.core.spi.component.ProviderServices.getServices(ProviderServices.java:160)
      at com.sun.jersey.core.spi.factory.MessageBodyFactory.initReaders(MessageBodyFactory.java:176)
      at com.sun.jersey.core.spi.factory.MessageBodyFactory.init(MessageBodyFactory.java:162)
      at com.sun.jersey.api.client.Client.init(Client.java:342)
      at com.sun.jersey.api.client.Client.access$000(Client.java:118)
      at com.sun.jersey.api.client.Client$1.f(Client.java:191)
      at com.sun.jersey.api.client.Client$1.f(Client.java:187)
      at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:193)
      at com.sun.jersey.api.client.Client.<init>(Client.java:187)
      at com.sun.jersey.api.client.Client.<init>(Client.java:170)
      at com.sun.jersey.api.client.Client.create(Client.java:679)
      at TestEctstaRest.main(TestEctstaRest.java:50)

Thanks
Jayabalambika.R

**Comment by pavelbucek** [comment]
Hi Jayabalambika.R,

you are using JAX-RS 2.x APIs with Jersey 1.x, which implements JAX-RS 1.x. JAX-RS 1.x doesn't have any client API; the reason for the issue is obvious. You need to use Jersey 2.x, preferably 2.25.1 (latest stable release of JAX-RS 2.0).

Please take a look at the examples (https://github.com/jersey/jersey/tree/2.5.x/examples) and ideally start your project from pom present there, it is tested and guaranteed to work.

Regards,
Pavel
