### ISSUE TITLE
jersey filter return NullPointerException

### ISSUE THREAD

**Issue by pangguoming** [jersey/jersey#3633]
i add a filter for my jersey application, but sometimes it throw null pointer excetion ,how to fix it and what i am doing wrong?

my code:

> package com.hqdl.spcsis.api;

import java.io.IOException;

import javax.servlet.ServletConfig;
import javax.servlet.ServletContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.ws.rs.container.ContainerRequestContext;
import javax.ws.rs.container.ContainerRequestFilter;
import javax.ws.rs.container.PreMatching;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.Response;

import com.hqdl.spcsis.bean.SpUser;

/**
 * 对于request的过滤器
 * 过滤器主要是用来操纵请求和响应参数像HTTP头，URI和/或HTTP方法
 * Provider //这个是匹配后增加参数或者减少参数
 */
@PreMatching  //不知道为什么和后请求过滤器冲突,不能同时使用
public class PreRequestFilter implements ContainerRequestFilter {
	
	@Context  
    HttpServletRequest webRequest;  
      
	@Context  
    HttpServletResponse webResponse;
	
    @Context  
    ServletConfig servletConfig;  
  
    @Context  
    ServletContext servletContext; 
	
    @Override
    public void filter(ContainerRequestContext containerRequestContext) throws IOException {
    	String requestUrl = containerRequestContext.getUriInfo().getPath();
    	String requestMethod = containerRequestContext.getMethod();
    	SpUser user  = (SpUser)(webRequest.getSession().getAttribute("user"));    	
    	if(!"user/login".equals(requestUrl) && user==null){
    		containerRequestContext.abortWith(Response
                    .status(Response.Status.UNAUTHORIZED)
                    .entity("用户未登录或登录超期")
                    .build());
    		return ;
    	}
    	
    	/*if(!user.getPermission().find(requestUrl,requestMethod))
    	{
    		containerRequestContext.abortWith(Response
                    .status(Response.Status.FORBIDDEN)
                    .entity("用户无权操作此资源")
                    .build());
    		return ;
    	}*/
    	/*if (!"user/login".equals(requestUrl))
		{
    		containerRequestContext.abortWith(Response
                    .status(Response.Status.FORBIDDEN)
                    .entity("用户无权操作此资源")
                    .build());
    		return ;
		}*/
    }
}

i get the error:

严重: Servlet.service() for servlet [Jersey Web Application] in context with path [/spcsis-1.0] threw exception [java.lang.NullPointerException] with root cause
java.lang.NullPointerException
	at org.glassfish.jersey.server.spring.scope.RequestContextFilter$2.resetAttributes(RequestContextFilter.java:124)
	at org.glassfish.jersey.server.spring.scope.RequestContextFilter.filter(RequestContextFilter.java:137)
	at org.glassfish.jersey.server.ContainerFilteringStage$ResponseFilterStage.apply(ContainerFilteringStage.java:196)
	at org.glassfish.jersey.server.ContainerFilteringStage$ResponseFilterStage.apply(ContainerFilteringStage.java:163)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
	at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:442)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:434)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:329)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mrerhuo** [comment]
@pangguoming 你解决了权限管理过滤器问题没？

**Comment by pangguoming** [comment]
@mrerhuo  最后还是采用 spring mvc + shiro

**Comment by mrerhuo** [comment]
@pangguoming 我解决了。http://www.cnblogs.com/mrer/p/8267266.html

**Comment by pangguoming** [comment]
@mrerhuo nice
