### ISSUE TITLE
Proxy Issues in ConnectorProviders

### ISSUE THREAD

**Issue by leonard84** [jersey/jersey#3655]
Since the built-in Client uses `HttpURLConnection` and can only use a proxy if it is globally via system properties, I've looked into the other offered connector providers and stumbled onto some issues.

* JDK Connector seems to expect SSL even if a plain http is made
```
io.netty.handler.codec.DecoderException: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 474554202f20485454502f312e310d0a4163636570743a206170706c69636174696f6e2f6a736f6e0d0a557365722d4167656e743a204a65727365792f322e32362d62303920284a444b20636f6e6e6563746f72290d0a486f73743a206c6f63616c686f73743a313038300d0a436f6e74656e742d4c656e6774683a20300d0a0d0a
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459) ~[netty-codec-4.1.12.Final.jar:4.1.12.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-codec-4.1.12.Final.jar:4.1.12.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.12.Final.jar:4.1.12.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.12.Final.jar:4.1.12.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.12.Final.jar:4.1.12.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-transport-4.1.12.Final.jar:4.1.12.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.12.Final.jar:4.1.12.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.12.Final.jar:4.1.12.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-transport-4.1.12.Final.jar:4.1.12.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134) [netty-transport-4.1.12.Final.jar:4.1.12.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-transport-4.1.12.Final.jar:4.1.12.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579) [netty-transport-4.1.12.Final.jar:4.1.12.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496) [netty-transport-4.1.12.Final.jar:4.1.12.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-transport-4.1.12.Final.jar:4.1.12.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.12.Final.jar:4.1.12.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [netty-common-4.1.12.Final.jar:4.1.12.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_141]
Caused by: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 474554202f20485454502f312e310d0a4163636570743a206170706c69636174696f6e2f6a736f6e0d0a557365722d4167656e743a204a65727365792f322e32362d62303920284a444b20636f6e6e6563746f72290d0a486f73743a206c6f63616c686f73743a313038300d0a436f6e74656e742d4c656e6774683a20300d0a0d0a
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1103) ~[netty-handler-4.1.12.Final.jar:4.1.12.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-codec-4.1.12.Final.jar:4.1.12.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-codec-4.1.12.Final.jar:4.1.12.Final]
```
* Connectors have different error handling if Proxy returns 403:
  *  Apache and Netty will return a response with 403
  *  Jdk fails with `java.io.IOException: "Connecting to proxy failed with status 403."` 
  * Grizzly and Jetty work for HTTP and return a response with 403
  * Jetty fails for HTTPS with `javax.ws.rs.ProcessingException: java.util.concurrent.ExecutionException: org.eclipse.jetty.client.HttpResponseException: Unexpected HttpResponse[HTTP/1.1 403 Forbidden]@3e3692a6 for HttpRequest[CONNECT localhost:1337 HTTP/1.1]@fdb79f3
`
  * GrizzlyConnector fails when the Proxy returns 403 when using `CONNECT` for HTTPS and blocks indefinetly. 
```
java.lang.NullPointerException: null
	at org.glassfish.grizzly.http.HttpClientFilter$ClientHttpResponseImpl.getProcessingState(HttpClientFilter.java:714) ~[grizzly-http-2.4.0.jar:2.4.0]
	at com.ning.http.client.providers.grizzly.HttpTransactionContext.currentTransaction(HttpTransactionContext.java:134) ~[grizzly-http-client-1.13.jar:na]
	at com.ning.http.client.providers.grizzly.AhcEventFilter.onHttpHeaderError(AhcEventFilter.java:261) ~[grizzly-http-client-1.13.jar:na]
	at org.glassfish.grizzly.http.HttpCodecFilter.handleRead(HttpCodecFilter.java:627) ~[grizzly-http-2.4.0.jar:2.4.0]
	at org.glassfish.grizzly.http.HttpClientFilter.handleRead(HttpClientFilter.java:175) ~[grizzly-http-2.4.0.jar:2.4.0]
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119) ~[grizzly-framework-2.4.0.jar:2.4.0]
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284) [grizzly-framework-2.4.0.jar:2.4.0]
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201) [grizzly-framework-2.4.0.jar:2.4.0]
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133) [grizzly-framework-2.4.0.jar:2.4.0]
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112) [grizzly-framework-2.4.0.jar:2.4.0]
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77) [grizzly-framework-2.4.0.jar:2.4.0]
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:539) [grizzly-framework-2.4.0.jar:2.4.0]
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112) [grizzly-framework-2.4.0.jar:2.4.0]
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117) [grizzly-framework-2.4.0.jar:2.4.0]
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56) [grizzly-framework-2.4.0.jar:2.4.0]
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137) [grizzly-framework-2.4.0.jar:2.4.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_141]
```

**Comment by megahall** [comment]
@leonard84 I can confirm I am seeing some similar really big failures with the Netty connector; it seems to be basically non-functional or almost totally untested, as far as I can see.

Using an HTTPS mode proxy on any mode resource doesn't work at all with the Netty connector. 

Using an HTTP mode proxy on an HTTPS mode resource erroneously sends a raw TLS 1.2 handshake message to the HTTP mode proxy socket, which causes the connection to fail on the proxy. The error never comes back up the stack because it happens deep inside some async code which jams forever and never makes forward progress.

You can tell the packet is a raw TLS 1.2 handshake because it begins with 0x160303, or handshake message version 3.3 (TLS 1.2).

Packet capture attached with an example:

<img width="1039" alt="netty_failure" src="https://user-images.githubusercontent.com/1231855/37943850-3c088826-312e-11e8-9073-e79cc82656d8.png">

The issue does not seem to happen with the Apache backend. So it seems like some documentation improvement or deprecation of broken or unsupported proxy clients is needed here, since nobody replied to this issue in six months.
