### ISSUE TITLE
Simple Post Problem using jersey-client version 2.26

### ISSUE THREAD

**Issue by luizconrado** [jersey/jersey#3704]
I am having problems doing a simple Post that works in the Jersey 2.25.1 but in the 2.26 version it fails (Using Java 8 144).

If I try to run the following code (that works in the 2.25.1 version), I get  an error:
Here is the code:
 
        Client client = ClientBuilder.newClient();
        WebTarget salesforceOAuth = client.target(credentials.get("endpoint"));
        credentials.remove("endpoint");

        Form oAuthForm = new Form();

        for (String key : credentials.keySet()) {
            oAuthForm.param(key, credentials.get(key));
        }

        Response response = salesforceOAuth
                .request(MediaType.APPLICATION_JSON).post(Entity.form(oAuthForm));

And here is the Error:
Exception in thread "main" java.lang.IllegalStateException: InjectionManagerFactory not found.
	at org.glassfish.jersey.internal.inject.Injections.lambda$lookupInjectionManagerFactory$0(Injections.java:98)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.glassfish.jersey.internal.inject.Injections.lookupInjectionManagerFactory(Injections.java:98)
	at org.glassfish.jersey.internal.inject.Injections.createInjectionManager(Injections.java:68)
	at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:432)
	at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:341)
	at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:826)
	at org.glassfish.jersey.client.ClientRequest.getConfiguration(ClientRequest.java:285)
	at org.glassfish.jersey.client.JerseyInvocation.validateHttpMethodAndEntity(JerseyInvocation.java:143)
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:112)
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:108)
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:99)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:445)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:351)
	at salesforce.OAuthToken.getToken(OAuthToken.java:37)
	at Main.main(Main.java:27)

Does anyone know what's going on?
Thank you

**Comment by yuHe1** [comment]
Please try to add jersey-hk2 jar to your classpath.

**Comment by luizconrado** [comment]
Hi yuHE1,

It worked just fine! Thank you.
One last question of I may. Is java 9 fully supported? If not, do you have any idea when java 9 will be fully supported? 
Thank you once again!
