### ISSUE TITLE
Problem using wink libraries with JAX-RS 2.0

### ISSUE THREAD

**Issue by pallavi253** [jersey/jersey#3782]
Hi,

We have one web application which has some dependencies on apache wink 1.2, which is built using JAX-RS1. 
We recently upgraded the weblogic to 12.2.1 which has inbuilt Jersey2.x , we started getting following exception at the time of deployment,

[[FATAL] A resource model has ambiguous (sub-)resource method for HTTP method GET and input mime-types as defined by"@Consumes" and
"@Produces" annotations at Java methods public org.apache.wink.common.model.app.AppService org.apache.wink.server.internal.resources
.RootResource.getServiceDocument(javax.ws.rs.core.UriInfo) and public org.apache.wink.common.model.app.AppService org.apache.wink.se
rver.internal.resources.RootResource.getServiceDocument(javax.ws.rs.core.UriInfo) at matching regular expression /. These two method
s produces and consumes exactly the same mime-types and therefore their invocation as a resource methods will always fail.; source='
org.glassfish.jersey.server.model.RuntimeResource@64b1c9e6']
        at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:555)
        at org.glassfish.jersey.server.ApplicationHandler.access$500(ApplicationHandler.java:184)
        at org.glassfish.jersey.server.ApplicationHandler$3.call(ApplicationHandler.java:350)
        at org.glassfish.jersey.server.ApplicationHandler$3.call(ApplicationHandler.java:347)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        Truncated. see log file for complete stacktrace
>
<Mar 9, 2018, 2:46:07,468 AM EST> <Error> <Deployer> <BEA-149231> <Unable to set the activation state to true for the application "p
roducts".
weblogic.application.ModuleException: org.glassfish.jersey.server.model.ModelValidationException: Validation of the application reso
urce model has failed during application initialization.
[[FATAL] A resource model has ambiguous (sub-)resource method for HTTP method GET and input mime-types as defined by"@Consumes" and
"@Produces" annotations at Java methods public org.apache.wink.common.model.app.AppService org.apache.wink.server.internal.resources
.RootResource.getServiceDocument(javax.ws.rs.core.UriInfo) and public org.apache.wink.common.model.app.AppService org.apache.wink.se
rver.internal.resources.RootResource.getServiceDocument(javax.ws.rs.core.UriInfo) at matching regular expression /. These two method
s produces and consumes exactly the same mime-types and therefore their invocation as a resource methods will always fail.; source='
org.glassfish.jersey.server.model.RuntimeResource@64b1c9e6']
        at weblogic.application.internal.ExtensibleModuleWrapper.start(ExtensibleModuleWrapper.java:140)
        at weblogic.application.internal.flow.ModuleListenerInvoker.start(ModuleListenerInvoker.java:124)
        at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:233)
        at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:228)
        at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:45)
        Truncated. see log file for complete stacktrace
Caused By: org.glassfish.jersey.server.model.ModelValidationException: Validation of the application resource model has failed durin
g application initialization.
[[FATAL] A resource model has ambiguous (sub-)resource method for HTTP method GET and input mime-types as defined by"@Consumes" and

Can anyone help me here?

Thanks in advance,
Pallavi

**Comment by pallavi253** [comment]
Can anyone please have a look at this issue?

**Comment by chkal** [comment]
Well, this actually looks like a Wink issue. Did you check for this ambiguity in Wink?
